language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-puppeteer' ]; then cd .. && eval "mv $currentfolder generator-puppeteer" && cd generator-puppeteer; fi

